Transfer GFF data to any CPlugin using SCORCO functions
nwn2dev/nwnx4 pull request #50
Opened 2022-05-31 10:32 UTC by CromFr

This PR adds new optional CPlugin ABI endpoints for sending and receiving GFF data, using the `StoreCampaignObject` and `RetrieveCampaignObject` NWScript functions.

The SCORCO hooking code has been moved from the SQL plugins into the nwnx4 hook dll, and nwnx4 will now always hook the SCORCO functions and forward the call to either:
- A loaded CPlugin if the `sDatabase` argument is in the form `NWNX.<plugin_class>`
- A legacy plugin registered with the SQL class if `sDatabase` is `NWNX`. This is to ensure existing NWScript code will still work without any modification.
- NWN2 campaign database if sDatabase  does not match any of the above

TODO:
- [ ] Test what happens if using an old SQL plugins that hooks the SCORCO functions a second time
- [ ] Double check that there's no conflicts with xp_craft (I believe xp_craft modifies the campaign database files, and does nothing special with SCORCO functions)

2022-07-24 22:17 UTC, scottmunday84 commented
I'm approving, but I have questions:

* Am I getting that we are using uint8_t* to get/set from a size of bytes?
* In most cases, a GFF will not be touched on set or get. Are these plugins purpose to just set or get without interpretation?

...and suggestions:

* GetGFF and SetGFF makes sense (General File Format, I'm guessing), but they might confuse those who are used to SCORCO terms (SetCampaignObject/ReadCampaignObject)
* The repo shouldn't include any compiled code; suggest we drop the NCS file in unit tests

2022-07-24 22:19 UTC, scottmunday84 requested changes
I'll approve, but I have questions:

* Am I getting that we are using uint8_t* to get/set from a size of bytes?
* In most cases, a GFF will not be touched on set or get. Are these plugins purpose to just set or get without interpretation?

...and suggestions:

* GetGFF and SetGFF makes sense (General File Format, I'm guessing), but they might confuse those who are used to SCORCO terms (SetCampaignObject/ReadCampaignObject)
* The repo shouldn't include any compiled code; suggest we drop the NCS file in unit tests

2022-07-25 18:12 UTC, CromFr commented
> Am I getting that we are using uint8_t* to get/set from a size of bytes?

`uint8_t*` are used for buffers that are meant to be written by plugins (output buffers), whereas `const uint8_t*` are meant to be only used.
For GetGFF, nwnx4 provides a buffer for storing the result (this buffer needs to be allocated by the nwn2 memory manager), and the plugin must write its GFF data into the buffer.
For SetGff, nwn2 generates GFF data that the plugin can read.

> Are these plugins purpose to just set or get without interpretation?

Plugins can receive raw GFF data (that they may want to parse / store somewhere) with SetGFF, and send GFF data with GetGFF.

> GetGFF and SetGFF makes sense (General File Format, I'm guessing), but they might confuse those who are used to SCORCO terms (SetCampaignObject/ReadCampaignObject)

For SCORCO, the functions are StoreCampaignObject / RetrieveCampaignObject. I followed the GetXXX / SetXXX / ... conventions, since they are similar to GetString and SetString, and it doesn't necessarily "store" anything. For example, a plugin could use the GetGFF endpoint to parse GFF data, extract some useful information and store only those information.

> The repo shouldn't include any compiled code; suggest we drop the NCS file in unit tests
I totally agree, however we would need to configure the CI to install the nwscript compiler and include scripts, and compile everything in the CI. Also, contributors would need to compile those scripts in order to test their changes (though I don't think it would be a big deal).

This could be addressed in another PR, but I'm not sure it's worth spending time on this :)

2022-07-25 22:59 UTC, scottmunday84 approved these changes

2022-07-26 07:12 UTC, merged