[Locked by #55] Bugfix loglevel selection
nwn2dev/nwnx4 pull request #58
Opened 2022-09-20 21:14 UTC by CromFr

2022-09-21 20:59 UTC, CromFr commented on src/plugins/xp_bugfix/xp_bugfix.ini
> +# TODO
@SkywingvL I found this undocumented key. Is it still relevant ?

2022-09-26 13:55 UTC, scottmunday84 requested changes
It might be better to place a reference to the logger at the end of the NWNX struct that is passed to all DLLs built in NWNX4. It would be backwards compatible, and would guarantee the version of this shared variable is available to all these internal built plugins.

2022-09-26 19:20 UTC, CromFr commented
This would mean sharing C++ objects with the plugin DLLs, and the whole point of the CPlugin ABI is to have a simple and basic interface that any language can implement.

Also xp_bugfix is not a CPlugin, it's a "legacy" C++ Plugin class ;)

2022-10-05 13:42 UTC, scottmunday84 approved these changes
In my original comment, I was speaking to the struct passed via the Detours API, but I can see that bugfix does things differently. I'm ok with adding an extern(al) defined variable, although overall it isn't always the best practice.

2022-10-05 14:12 UTC, merged